version: '3.8'

services:
  co2-backend:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env


  db:
    image: postgres:15
    container_name: local_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Satire6Digits
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
